" Pathogen: https://github.com/tpope/vim-pathogen
" mkdir -p ~/.vim/autoload ~/.vim/bundle && \
" curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
execute pathogen#infect()
syntax on
filetype plugin indent on

" Colorscheme
set t_Co=256
colorscheme srcery

" Enable line numbers
set number
set numberwidth=3
highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE

" Vim-Sensible: https://github.com/tpope/vim-sensible
" cd ~/.vim/bundle && \
" git clone https://github.com/tpope/vim-sensible.git

" NerdCommenter: https://github.com/scrooloose/nerdcommenter
" cd ~/.vim/bundle && \
" git clone https://github.com/scrooloose/nerdcommenter.git
" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1

" Align line-wise comment delimiters flush left instead of following code
" indentation
let g:NERDDefaultAlign = 'left'

" Set a language to use its alternate delimiters by default
let g:NERDAltDelims_java = 1

" Add your own custom formats or override the defaults
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }

" Allow commenting and inverting empty lines (useful when commenting a
" region)
let g:NERDCommentEmptyLines = 1

" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1

" Enable NERDCommenterToggle to check all selected lines is commented or not 
let g:NERDToggleCheckAllLines = 1

" Vim-Airline
" git clone https://github.com/vim-airline/vim-airline
" ~/.vim/bundle/vim-airline

" Automatically displays all buffers when there's only one tab open.
let g:airline#extensions#tabline#enabled = 1

